### ISSUE TITLE
Can't connect to dev-node.substrate.dev

### ISSUE THREAD

**Issue by JoshOrndorff** [substrate-developer-hub/substrate-front-end#9]
Using commit 20d1b34930d0314 I can't get connected to the node at wss://dev-node.substrate.dev:9944

This worked as recently as last week, but now I get an error about missing types.
![types error](https://user-images.githubusercontent.com/2915325/64467662-3eab6500-d0c7-11e9-895a-789f03d3f792.png)

**Comment by shawntabrizi** [comment]
Solved with https://github.com/substrate-developer-hub/substrate-front-end/pull/10

Needed the newest Polkadot JS API Beta
